function out = tmp_smart_solver_syntax_check(varargin)
% Auto-generated by EIDAT Smart Solver MATLAB export.
% Prediction usage: y = tmp_smart_solver_syntax_check(Input1, control_period)
% Metadata usage: meta = tmp_smart_solver_syntax_check('metadata')
% Inputs: Input1 (Input1) [u], control period (control_period)
% Output: y is predicted Output; scalar and array inputs are evaluated element-wise.
% Call with 'metadata' to inspect equation text, normalization, solver stats, and imported variable definitions.

% Validation example from one cached EIDAT fit point.
% Copy the lines inside the `if false` block into the MATLAB Command Window or a script to validate the export.
if false
    % Cached fit point: run=CondA, serial=SN-001, observation=obs-1
    meta = tmp_smart_solver_syntax_check('metadata');
    Input1 = 1;
    control_period = 30;
    pred = tmp_smart_solver_syntax_check(Input1, control_period);
    actual_mean = 11;
    fprintf('Equation: %s\n', meta.equation_text);
    fprintf('Predicted Output: %.12g\n', pred);
    fprintf('Cached actual_mean: %.12g\n', actual_mean);
    fprintf('Absolute delta vs actual_mean: %.12g\n', abs(pred - actual_mean));
end

if nargin == 1
    request = varargin{1};
    if (ischar(request) || (isstring(request) && isscalar(request))) && strcmpi(char(request), 'metadata')
        out = local_metadata();
        return;
    end
end
if nargin ~= 2
    error('tmp_smart_solver_syntax_check:Usage', 'Usage: y = tmp_smart_solver_syntax_check(Input1, control_period); meta = tmp_smart_solver_syntax_check(''metadata'');');
end
Input1 = varargin{1};
control_period = varargin{2};
out = eidat_perf_curve_cp_predict(Input1, eidat_perf_clamp(control_period, 10, 50), {[0 1], [0 2], [3]}, 0, 1, 0, 1);
end

function meta = local_metadata()
meta = struct();
meta.output_target = 'Output';
meta.output_units = 'u';
meta.input_targets = {'Input1'};
meta.input_units = {'u'};
meta.input_roles = {'Primary'};
meta.argument_names = {'Input1', 'control_period'};
meta.equation_text = 'y = curve_cp(x, cp)';
meta.normalization_text = 'x'' = (x - 0) / 1 ; cp'' = (cp - 0) / 1';
meta.fit_family = 'quadratic_curve_control_period';
meta.fit_family_label = 'Quadratic Curve + Control Period';
meta.solver_branch = 'quadratic_curve_control_period';
meta.selection_reason = 'Curve CP selected.';
meta.uses_control_period = true;
meta.uses_staged_mediator = false;
meta.selected_control_period = 30;
meta.rmse = 1.5;
meta.residual_threshold = 3;
meta.in_fit_percent = 80;
meta.in_fit_count = 8;
meta.fell_out_count = 2;
meta.fell_out_percent = 20;
meta.sample_count = 10;
meta.warning_text = 'Check support slices.';
meta.run_count = 1;
meta.serial_count = 1;
meta.stage2_fit_source = '';
meta.mediator_clamp_count = 0;
meta.asset_type = '';
meta.asset_specific_type = '';
meta.filter_summary = '';
meta.config_text = '';
end

% Piecewise linear predictor used by exported piecewise performance equations.
% Inputs: x values, coefficient vector, and breakpoint vector.
% Output: y predictions with hinge terms applied element-wise.
function y = eidat_perf_piecewise_predict(x, coeffs, breakpoints)
x = double(x);
y = coeffs(1) + coeffs(2).*x;
for idx = 1:numel(breakpoints)
    y = y + coeffs(idx + 2).*max(0, x - breakpoints(idx));
end
end

% Monotone PCHIP predictor used by exported monotone performance equations.
% Inputs: x values, knot locations, knot values, and left/right clamp values.
% Output: y predictions with PCHIP interpolation and end clamping.
function y = eidat_perf_pchip_predict(x, knots, knot_values, left_y, right_y)
x = double(x);
y = interp1(knots, knot_values, x, 'pchip');
y(x < knots(1)) = left_y;
y(x > knots(end)) = right_y;
end

% Control-period-aware quadratic curve predictor used by exported 2D CP equations.
% Inputs: x, control_period, coefficient polynomials, and normalization terms.
% Output: y predictions evaluated element-wise over the normalized 2D curve basis terms.
function y = eidat_perf_curve_cp_predict(x, control_period, coeff_cp_models, x_center, x_scale, cp_center, cp_scale)
xn = (double(x) - x_center) ./ x_scale;
cpn = (double(control_period) - cp_center) ./ cp_scale;
basis = {xn.^2, xn, ones(size(xn))};
y = zeros(size(xn));
for idx = 1:min(numel(coeff_cp_models), numel(basis))
    coeffs = coeff_cp_models{idx};
    y = y + polyval(coeffs, cpn) .* basis{idx};
end
end

% Control-period-aware quadratic surface predictor for exported 3D equations.
% Inputs: x1, x2, control_period, coefficient polynomials, and normalization terms.
% Output: y predictions evaluated element-wise over the normalized basis terms.
function y = eidat_perf_surface_cp_predict(x1, x2, control_period, coeff_cp_models, x1_center, x1_scale, x2_center, x2_scale, cp_center, cp_scale)
x1n = (double(x1) - x1_center) ./ x1_scale;
x2n = (double(x2) - x2_center) ./ x2_scale;
cpn = (double(control_period) - cp_center) ./ cp_scale;
basis = {ones(size(x1n)), x1n, x2n, x1n.^2, x1n.*x2n, x2n.^2};
y = zeros(size(x1n));
for idx = 1:min(numel(coeff_cp_models), numel(basis))
    coeffs = coeff_cp_models{idx};
    y = y + polyval(coeffs, cpn) .* basis{idx};
end
end

% Quadratic 3-input predictor used by exported Smart Solver equations.
% Inputs: x1, x2, x3, coefficient vector, and normalization terms.
% Output: y predictions evaluated element-wise over the normalized 3-input basis terms.
function y = eidat_perf_three_input_predict(x1, x2, x3, coeffs, x1_center, x1_scale, x2_center, x2_scale, x3_center, x3_scale)
x1n = (double(x1) - x1_center) ./ x1_scale;
x2n = (double(x2) - x2_center) ./ x2_scale;
x3n = (double(x3) - x3_center) ./ x3_scale;
basis = {ones(size(x1n)), x1n, x2n, x3n, x1n.^2, x2n.^2, x3n.^2, x1n.*x2n, x1n.*x3n, x2n.*x3n};
y = zeros(size(x1n));
coeffs = double(coeffs);
for idx = 1:min(numel(coeffs), numel(basis))
    y = y + coeffs(idx) .* basis{idx};
end
end

% Control-period-aware quadratic 3-input predictor used by exported Smart Solver equations.
% Inputs: x1, x2, x3, control_period, coefficient polynomials, and normalization terms.
% Output: y predictions evaluated element-wise over the normalized 3-input basis terms.
function y = eidat_perf_three_input_cp_predict(x1, x2, x3, control_period, coeff_cp_models, x1_center, x1_scale, x2_center, x2_scale, x3_center, x3_scale, cp_center, cp_scale)
x1n = (double(x1) - x1_center) ./ x1_scale;
x2n = (double(x2) - x2_center) ./ x2_scale;
x3n = (double(x3) - x3_center) ./ x3_scale;
cpn = (double(control_period) - cp_center) ./ cp_scale;
basis = {ones(size(x1n)), x1n, x2n, x3n, x1n.^2, x2n.^2, x3n.^2, x1n.*x2n, x1n.*x3n, x2n.*x3n};
y = zeros(size(x1n));
for idx = 1:min(numel(coeff_cp_models), numel(basis))
    coeffs = coeff_cp_models{idx};
    y = y + polyval(coeffs, cpn) .* basis{idx};
end
end

% Clamp helper used by exported staged Smart Solver equations.
% Inputs: x values and lower/upper bounds.
% Output: x clamped element-wise to the provided bounds.
function y = eidat_perf_clamp(x, lower_bound, upper_bound)
y = min(max(double(x), lower_bound), upper_bound);
end
